packages:
  - packages/*

catalogs:
  dev:
    '@vitejs/plugin-vue': ^6.0.6
    '@vitejs/plugin-vue-jsx': ^5.1.5
    conventional-changelog-cli: ^5.0.0
    eslint: ^8.57.1
    eslint-config-h21: ^0.17.0
    eslint-plugin-lit: ^1.15.0
    minimist: ^1.2.8
    tsdown: ^0.22.0
    turbo: ^2.9.12
    typescript: ^6.0.3
    vite: ^8.0.12
  prod:
    '@vueuse/core': ^14.3.0
    lit: ^3.3.2
    react: ^19.2.6
    react-dom: ^19.2.6
    vue: ^3.5.34
    vue-router: ^5.0.6
  types:
    '@types/node': '>=22'
    '@types/react': '^19.2.14'
    '@types/react-dom': ^19.2.3
